-- Logins that have gone out to a SAML provider and not yet come back.
--
-- A service provider must refuse an assertion answering a request nobody made,
-- which means remembering the request id between sending somebody to the
-- provider and their assertion arriving. OIDC keeps the equivalent state in a
-- cookie, and SAML cannot: the assertion arrives as a form POST from the
-- provider's own origin, and a SameSite=Lax cookie is precisely what a browser
-- will not send on a cross-site POST. Loosening the session cookie to
-- SameSite=None to make that work would trade a real protection for a detail of
-- one flow.
--
-- So the ids live here instead, which also means a login survives landing on a
-- different replica than the one that started it.
CREATE TABLE saml_requests (
    -- The AuthnRequest ID, as sent. Not a UUID: the value is generated by the
    -- SAML library in the form providers expect.
    id         TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Short: this is the window somebody has to finish signing in, not a
    -- credential. Expired rows are swept, and an expired id stops being
    -- accepted whether or not the sweep has got to it.
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_saml_requests_expires ON saml_requests (expires_at);
